/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/dashboard': typeof StaffDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/dashboard': typeof StaffDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/staff/dashboard': typeof StaffDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/booking-confirmed'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/admin/dashboard'
    | '/staff/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/booking-confirmed'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/admin/dashboard'
    | '/staff/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/booking-confirmed'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/admin/dashboard'
    | '/staff/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
